name: CI - test and build
run-name: ${{github.actor}} running test and build on ${{github.ref_name}}

on:
  push:
    branches:
      - '*'
  pull_request:

permissions:
  contents: read
  packages: write
  checks: write

jobs:
  test-ui:
    name: UI — lint & test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install UI dependencies
        run: npm --prefix apps/ui ci

      - name: Run lint
        run: npm --prefix apps/ui run lint

      - name: Run tests
        run: npm --prefix apps/ui run test -- --watch=false --browsers=ChromeHeadless

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: apps/ui/test-results/junit-results.xml

      - name: Display Test Report
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: Angular Unit Tests
          path: apps/ui/test-results/junit-results.xml
          reporter: java-junit

  build-api:
    name: API — build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install API dependencies
        run: npm --prefix apps/api ci

      - name: Build API
        run: npm --prefix apps/api run build
